### ISSUE TITLE
scrollingSpeed

### ISSUE THREAD

**Issue by chamilcar** [alvarotrigo/pagePiling.js#139]
Hi, I added a new value for scrollingSpeed in the header but I can´t notice any change. I´ve also tried to change the default value in jquery.pagepiling.min.js from 700 to different values without achieving any changes.

**Comment by alvarotrigo** [comment]
If you use `css3: true`, which is the default one, then you have to change it [in the CSS file](https://github.com/alvarotrigo/pagePiling.js/blob/master/jquery.pagepiling.css#L22) line 22 where you find:

```css
.pp-easing {
    -webkit-transition: all 1000ms cubic-bezier(0.550, 0.085, 0.000, 0.990);
    -moz-transition: all 1000ms cubic-bezier(0.550, 0.085, 0.000, 0.990);
    -o-transition: all 1000ms cubic-bezier(0.550, 0.085, 0.000, 0.990);
    transition: all 1000ms cubic-bezier(0.550, 0.085, 0.000, 0.990);
    /* custom */
    -webkit-transition-timing-function: cubic-bezier(0.550, 0.085, 0.000, 0.990);
    -moz-transition-timing-function: cubic-bezier(0.550, 0.085, 0.000, 0.990);
    -o-transition-timing-function: cubic-bezier(0.550, 0.085, 0.000, 0.990);
    transition-timing-function: cubic-bezier(0.550, 0.085, 0.000, 0.990);
    /* custom */
}
```

Just change the `1000` value for any other you want.
