### ISSUE TITLE
pp-scrollable section  is way to sticky on iPhones

### ISSUE THREAD

**Issue by pallavi-talwar** [alvarotrigo/pagePiling.js#149]
Hi, 

On iPhones the pp-scrollable sections are too sticky and the user needs to drag scroll multiple times for it to scroll properly. Can you tell me how to fix it?

**Comment by alvarotrigo** [comment]
Try using this:

```css
* {
    -webkit-overflow-scrolling: touch;
}
```
